In [10]:
import os
os.listdir()

['.ipynb_checkpoints',
 'data.txt',
 'newsmallgray.png',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Untitled.ipynb']

In [11]:
import pandas

In [12]:
df1=pandas.read_csv("supermarkets.csv")
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [13]:
df2=pandas.read_json("supermarkets.json")
df2

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [14]:
df3=pandas.to_json(df2)

AttributeError: module 'pandas' has no attribute 'to_json'

In [ ]:
data = pandas.read_json('http://api.population.io/')
print(data)

In [6]:
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [7]:
dfs3=pandas.read_excel("supermarkets.xlsx", sheet_name=0)
dfs3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [8]:
df4=pandas.read_csv("supermarkets-commas.txt")
df4

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [9]:
df5=pandas.read_csv("supermarkets-semi-colons.txt",sep=";")
df5

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [5]:
df7=pandas.read_json("supermarkets.json")
df7

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [6]:
df7=df7.set_index("Address")

In [12]:
list(df7.loc[:,"Country"])

['USA', 'USA', 'USA', 'USA', 'USA', 'USA']

In [7]:
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [14]:
df7.iloc[3,1:4]

City       San Francisco
State           CA 94114
Country              USA
Name: 3995 23rd St, dtype: object

In [60]:
df7.drop("City",1)

C:\Users\jeyaprakash_dasu_raj\AppData\Local\Temp/ipykernel_36456/3298495432.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df7.drop("City",1)


ID             State Country         Name  Employees
Address                                                              
3666 21st St      1          CA 94114     USA      Madeira          8
735 Dolores St    2          CA 94119     USA  Bready Shop         15
332 Hill St       3  California 94114     USA  Super River         25
3995 23rd St      4          CA 94114     USA   Ben's Shop         10
1056 Sanchez St   5        California     USA      Sanchez         12
551 Alvarado St   6          CA 94114     USA   Richvalley         20

In [61]:
df7


ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [62]:
df7.drop("332 Hill St",0)

C:\Users\jeyaprakash_dasu_raj\AppData\Local\Temp/ipykernel_36456/2526208556.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df7.drop("332 Hill St",0)


ID           City       State Country         Name  Employees
Address                                                                       
3666 21st St      1  San Francisco    CA 94114     USA      Madeira          8
735 Dolores St    2  San Francisco    CA 94119     USA  Bready Shop         15
3995 23rd St      4  San Francisco    CA 94114     USA   Ben's Shop         10
1056 Sanchez St   5  San Francisco  California     USA      Sanchez         12
551 Alvarado St   6  San Francisco    CA 94114     USA   Richvalley         20

In [63]:
df7


ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [66]:
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [68]:
df7.drop(df7.columns[0:3],1)

C:\Users\jeyaprakash_dasu_raj\AppData\Local\Temp/ipykernel_36456/2806056389.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df7.drop(df7.columns[0:3],1)


Country         Name  Employees
Address                                        
3666 21st St        USA      Madeira          8
735 Dolores St      USA  Bready Shop         15
332 Hill St         USA  Super River         25
3995 23rd St        USA   Ben's Shop         10
1056 Sanchez St     USA      Sanchez         12
551 Alvarado St     USA   Richvalley         20

In [18]:
df7.index

NameError: name 'df7' is not defined

In [16]:
df7.columns

Index(['ID', 'City', 'State', 'Country', 'Name', 'Employees'], dtype='object')

In [17]:
len(df7.index)

6

In [18]:
df7["Continent"]=df7.shape[0]*["North America"]
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees      Continent  
Address                                    
3666 21st St             8  North America  
735 Dolores St          15  North America  
332 Hill St             25  North America  
3995 23rd St            10  North America  
1056 Sanchez St         12  North America  
551 Alvarado St         20  North America

In [19]:
df7.shape[0]*["North Americas"]

['North Americas',
 'North Americas',
 'North Americas',
 'North Americas',
 'North Americas',
 'North Americas']

In [20]:
df7["Continent"]=df7.shape[0]*["North America"]

In [21]:
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees      Continent  
Address                                    
3666 21st St             8  North America  
735 Dolores St          15  North America  
332 Hill St             25  North America  
3995 23rd St            10  North America  
1056 Sanchez St         12  North America  
551 Alvarado St         20  North America

In [22]:
df7["Continent"]=df7["Country"]+","+"Narayana"

In [23]:
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees     Continent  
Address                                   
3666 21st St             8  USA,Narayana  
735 Dolores St          15  USA,Narayana  
332 Hill St             25  USA,Narayana  
3995 23rd St            10  USA,Narayana  
1056 Sanchez St         12  USA,Narayana  
551 Alvarado St         20  USA,Narayana

In [24]:
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees     Continent  
Address                                   
3666 21st St             8  USA,Narayana  
735 Dolores St          15  USA,Narayana  
332 Hill St             25  USA,Narayana  
3995 23rd St            10  USA,Narayana  
1056 Sanchez St         12  USA,Narayana  
551 Alvarado St         20  USA,Narayana

In [25]:
df7_t=df7.T

In [26]:
df7_t

Address     3666 21st St 735 Dolores St       332 Hill St   3995 23rd St  \
ID                     1              2                 3              4   
City       San Francisco  San Francisco     San Francisco  San Francisco   
State           CA 94114       CA 94119  California 94114       CA 94114   
Country              USA            USA               USA            USA   
Name             Madeira    Bready Shop       Super River     Ben's Shop   
Employees              8             15                25             10   
Continent   USA,Narayana   USA,Narayana      USA,Narayana   USA,Narayana   

Address   1056 Sanchez St 551 Alvarado St  
ID                      5               6  
City        San Francisco   San Francisco  
State          California        CA 94114  
Country               USA             USA  
Name              Sanchez      Richvalley  
Employees              12              20  
Continent    USA,Narayana    USA,Narayana

In [27]:
df7_t["My address"]=[7,"My City","My country",10,"My shop","My state","My Continent"]

In [28]:
df7_t

Address     3666 21st St 735 Dolores St       332 Hill St   3995 23rd St  \
ID                     1              2                 3              4   
City       San Francisco  San Francisco     San Francisco  San Francisco   
State           CA 94114       CA 94119  California 94114       CA 94114   
Country              USA            USA               USA            USA   
Name             Madeira    Bready Shop       Super River     Ben's Shop   
Employees              8             15                25             10   
Continent   USA,Narayana   USA,Narayana      USA,Narayana   USA,Narayana   

Address   1056 Sanchez St 551 Alvarado St    My address  
ID                      5               6             7  
City        San Francisco   San Francisco       My City  
State          California        CA 94114    My country  
Country               USA             USA            10  
Name              Sanchez      Richvalley       My shop  
Employees              12              20      My state  
Continent    USA,Narayana    USA,Narayana  My Continent

In [29]:
df7_t["332 Hill St"]=[7,"My City","My country",10,"My shop","My state","My Continent"]

In [30]:
df7_t

Address     3666 21st St 735 Dolores St   332 Hill St   3995 23rd St  \
ID                     1              2             7              4   
City       San Francisco  San Francisco       My City  San Francisco   
State           CA 94114       CA 94119    My country       CA 94114   
Country              USA            USA            10            USA   
Name             Madeira    Bready Shop       My shop     Ben's Shop   
Employees              8             15      My state             10   
Continent   USA,Narayana   USA,Narayana  My Continent   USA,Narayana   

Address   1056 Sanchez St 551 Alvarado St    My address  
ID                      5               6             7  
City        San Francisco   San Francisco       My City  
State          California        CA 94114    My country  
Country               USA             USA            10  
Name              Sanchez      Richvalley       My shop  
Employees              12              20      My state  
Continent    USA,Narayana    USA,Narayana  My Continent

In [31]:
df7=df7_t.T

In [32]:
df7

ID           City       State Country         Name Employees  \
Address                                                                        
3666 21st St     1  San Francisco    CA 94114     USA      Madeira         8   
735 Dolores St   2  San Francisco    CA 94119     USA  Bready Shop        15   
332 Hill St      7        My City  My country      10      My shop  My state   
3995 23rd St     4  San Francisco    CA 94114     USA   Ben's Shop        10   
1056 Sanchez St  5  San Francisco  California     USA      Sanchez        12   
551 Alvarado St  6  San Francisco    CA 94114     USA   Richvalley        20   
My address       7        My City  My country      10      My shop  My state   

                    Continent  
Address                        
3666 21st St     USA,Narayana  
735 Dolores St   USA,Narayana  
332 Hill St      My Continent  
3995 23rd St     USA,Narayana  
1056 Sanchez St  USA,Narayana  
551 Alvarado St  USA,Narayana  
My address       My Continent

In [33]:
type(df7)

pandas.core.frame.DataFrame

In [34]:
df7

ID           City       State Country         Name Employees  \
Address                                                                        
3666 21st St     1  San Francisco    CA 94114     USA      Madeira         8   
735 Dolores St   2  San Francisco    CA 94119     USA  Bready Shop        15   
332 Hill St      7        My City  My country      10      My shop  My state   
3995 23rd St     4  San Francisco    CA 94114     USA   Ben's Shop        10   
1056 Sanchez St  5  San Francisco  California     USA      Sanchez        12   
551 Alvarado St  6  San Francisco    CA 94114     USA   Richvalley        20   
My address       7        My City  My country      10      My shop  My state   

                    Continent  
Address                        
3666 21st St     USA,Narayana  
735 Dolores St   USA,Narayana  
332 Hill St      My Continent  
3995 23rd St     USA,Narayana  
1056 Sanchez St  USA,Narayana  
551 Alvarado St  USA,Narayana  
My address       My Continent

In [35]:
df7

ID           City       State Country         Name Employees  \
Address                                                                        
3666 21st St     1  San Francisco    CA 94114     USA      Madeira         8   
735 Dolores St   2  San Francisco    CA 94119     USA  Bready Shop        15   
332 Hill St      7        My City  My country      10      My shop  My state   
3995 23rd St     4  San Francisco    CA 94114     USA   Ben's Shop        10   
1056 Sanchez St  5  San Francisco  California     USA      Sanchez        12   
551 Alvarado St  6  San Francisco    CA 94114     USA   Richvalley        20   
My address       7        My City  My country      10      My shop  My state   

                    Continent  
Address                        
3666 21st St     USA,Narayana  
735 Dolores St   USA,Narayana  
332 Hill St      My Continent  
3995 23rd St     USA,Narayana  
1056 Sanchez St  USA,Narayana  
551 Alvarado St  USA,Narayana  
My address       My Continent

In [4]:
df7

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [5]:
import geopy
dir(geopy)

['AlgoliaPlaces',
 'ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'BaiduV3',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'Geocodio',
 'Geolake',
 'GoogleV3',
 'Here',
 'HereV7',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'MapQuest',
 'MapTiler',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'What3WordsV3',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '__version_info__',
 'adapters',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'get_version',
 'location',
 'point',
 'timezone',
 'units',
 'util']

In [6]:
type(df7)

pandas.core.frame.DataFrame

In [19]:
from geopy.geocoders import ArcGIS

In [20]:
nom=ArcGIS()

In [21]:
n=nom.geocode("735 Dolores St, San Francisco, CA 94114")

In [22]:
n.latitude

37.757828979640195

In [23]:
n.longitude

-122.4253730300932

In [24]:
type(n)

geopy.location.Location

In [30]:
df=pandas.read_csv("supermarkets.csv")

In [31]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [32]:
df["Address"]=df["Address"]+"," +df["City"]+"," +df["State"]+"," +df["Country"]

In [33]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [34]:
df["Coordinates"]=df["Address"].apply(nom.geocode)
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [36]:
df.Coordinates

0    (3666 21st St, San Francisco, California, 9411...
1    (735 Dolores St, San Francisco, California, 94...
2    (332 Hill St, San Francisco, California, 94114...
3    (3995 23rd St, San Francisco, California, 9411...
4    (1056 Sanchez St, San Francisco, California, 9...
5    (551 Alvarado St, San Francisco, California, 9...
Name: Coordinates, dtype: object

In [37]:
df.Coordinates[0].latitude

37.756632001957215

In [38]:
df7

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [39]:
df.Coordinates

0    (3666 21st St, San Francisco, California, 9411...
1    (735 Dolores St, San Francisco, California, 94...
2    (332 Hill St, San Francisco, California, 94114...
3    (3995 23rd St, San Francisco, California, 9411...
4    (1056 Sanchez St, San Francisco, California, 9...
5    (551 Alvarado St, San Francisco, California, 9...
Name: Coordinates, dtype: object

In [41]:
df.Coordinates[0]

Location(3666 21st St, San Francisco, California, 94114, (37.756632001957215, -122.42941101194798, 0.0))

In [42]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [47]:
df["Latitudes"]=df["Coordinates"].apply(lambda x: x.latitude if x != None else None)

In [48]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  Latitudes  
0  (3666 21st St, San Francisco, California, 9411...  37.756632  
1  (735 Dolores St, San Francisco, California, 94...  37.757829  
2  (332 Hill St, San Francisco, California, 94114...  37.755845  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582

In [46]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  Latitudes  
0  (3666 21st St, San Francisco, California, 9411...  37.756632  
1  (735 Dolores St, San Francisco, California, 94...  37.757829  
2  (332 Hill St, San Francisco, California, 94114...  37.755845  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582

In [50]:
df["Longitude"]=df["Coordinates"].apply(lambda x: x.longitude if x != None else None)

In [51]:
df

ID                                         Address           City  \
0   1         3666 21st St,San Francisco,CA 94114,USA  San Francisco   
1   2       735 Dolores St,San Francisco,CA 94119,USA  San Francisco   
2   3  332 Hill St,San Francisco,California 94114,USA  San Francisco   
3   4         3995 23rd St,San Francisco,CA 94114,USA  San Francisco   
4   5    1056 Sanchez St,San Francisco,California,USA  San Francisco   
5   6      551 Alvarado St,San Francisco,CA 94114,USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  Latitudes   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756632 -122.429411  
1  (735 Dolores St, San Francisco, California, 94...  37.757829 -122.425373  
2  (332 Hill St, San Francisco, California, 94114...  37.755845 -122.428813  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921 -122.431703  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132 -122.430006  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582 -122.433234

In [52]:
[[123,22,123,44,123],[],[]]

[[123, 22, 123, 44, 123], [], []]

In [53]:
import numpy

In [55]:
n=numpy.arange(27)

In [56]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [57]:
type(n)

numpy.ndarray

In [58]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [59]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [60]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [61]:
m=numpy.asarray([[123,22,123,44,123],[],[]])

C:\Users\jeyaprakash_dasu_raj\AppData\Local\Temp/ipykernel_10048/3627331245.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m=numpy.asarray([[123,22,123,44,123],[],[]])


In [62]:
m

array([list([123, 22, 123, 44, 123]), list([]), list([])], dtype=object)

In [63]:
print(m)

[list([123, 22, 123, 44, 123]) list([]) list([])]


In [64]:
type(m)

numpy.ndarray

In [65]:
import cv2

In [67]:
im_g=cv2.imread("smallgray.png",0)

In [68]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [69]:
im_g2=cv2.imread("smallgray.png",1)

In [70]:
im_g2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [71]:
print(im_g2)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [72]:
cv2.imwrite("newsmallgray.png",im_g2)

True

In [73]:
a=[1,2,3]

In [75]:
a[0:2]

[1, 2]

In [76]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [77]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [78]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [79]:
im_g.shape

(3, 5)

In [83]:
im_g[2,4]

182

In [85]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [86]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [87]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [92]:
ims=numpy.hstack((im_g,im_g,im_g))

In [93]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [100]:
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [101]:
ims=numpy.vstack((im_g,im_g,im_g))

In [102]:
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [106]:
lst=numpy.vsplit(ims,3)

In [107]:
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [108]:
type(lst)

list

In [109]:
lst[0]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [112]:
lst[0:1]

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]